# This GitHub Actions workflow is now configured to deploy to an in-workflow Ganache instance.
name: Smart Contract CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Contracts
        run: npx solhint 'contracts/**/*.sol'

      - name: Compile Contracts
        run: npx hardhat compile

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Slither Security Analysis
        run: |
          pip install slither-analyzer
          slither .

      - name: Run Tests
        run: npx hardhat test

      # --- Deployment Gate to Ganache ---
      # These steps only run on a push to the 'main' branch.

      - name: Start Ganache in Background
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          npm install -g ganache
          ganache --wallet.deterministic --chain.chainId 1337 &
          sleep 5 # Give Ganache a moment to start up

      - name: Deploy to Ganache
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        # We now target the 'ganache' network and our original 'deploy.js' script.
        run: npx hardhat run scripts/deploy.js --network ganache

